CREATE DATABASE BD_VENDAS;

USE BD_VENDAS;

CREATE TABLE TB_CLIENTE (
  ID_CLI INT PRIMARY KEY AUTO_INCREMENT,
  NOME_CLI VARCHAR(40) NOT NULL,
  TELCLI VARCHAR(14),
  CPFCLI VARCHAR(14),
  LOGRACLI VARCHAR(25),
  NUMRECLI INT,
  COMPLEMENTO VARCHAR(20),
  CEPCLI VARCHAR(9),
  BAIRROCLI VARCHAR(20),
  CIDADECLI VARCHAR(25),
  TIPOCLI INT NOT NULL
) ENGINE=INNODB;

CREATE TABLE TB_VENDEDOR (
  IDVEN INT PRIMARY KEY AUTO_INCREMENT,
  NOMEVEND VARCHAR(25),
  FUNCVEND VARCHAR(20)
) ENGINE=INNODB;

CREATE TABLE TB_PRODUTO (
  IDPROD INT PRIMARY KEY AUTO_INCREMENT,
  NOMEPROD VARCHAR(20) NOT NULL,
  VALORPROD DECIMAL(5,2),
  QTDPROD INT,
  MARCA VARCHAR(20),
  FORNPROF VARCHAR(20)
) ENGINE=INNODB;

CREATE TABLE TB_PEDIDO (
  IDPED INT PRIMARY KEY AUTO_INCREMENT,
  CODCLI INT NOT NULL,
  CODVEND INT NOT NULL,
  DATAPED DATE,
  TIPOENTREGA VARCHAR(20),
  FOREIGN KEY (CODCLI) REFERENCES TB_CLIENTE(ID_CLI),
  FOREIGN KEY (CODVEND) REFERENCES TB_VENDEDOR(IDVEN)
) ENGINE=INNODB;

CREATE TABLE TB_ITENS (
  IDITEM INT PRIMARY KEY AUTO_INCREMENT,
  CODPED INT NOT NULL,
  CODPROD INT NOT NULL,
  OBS VARCHAR(20),
  FOREIGN KEY (CODPED) REFERENCES TB_PEDIDO(IDPED),
  FOREIGN KEY (CODPROD) REFERENCES TB_PRODUTO(IDPROD)
) ENGINE=INNODB;


INSERT INTO TB_CLIENTE (NOME_CLI,TEL_CLI, CPFCLI ,LOGRACLI, NUMRECLI, COMPLEMENTO ,CEPCLI ,BAIRROCLI ,CIDADECLI, TIPOCLI) 
VALUES("RICCI","(16)99406-1610","49981246840","HIGIENOPOLIS",1037,37,15085-300,"CIDADE NOVA","SAO JOSE DO RIO PRETO","PREMIUM");

INSERT INTO TB_CLIENTE (NOME_CLI,TEL_CLI, CPFCLI ,LOGRACLI, NUMRECLI, COMPLEMENTO ,CEPCLI ,BAIRROCLI ,CIDADECLI, TIPOCLI) 
VALUES ("GABRIEL","(17)99678-1428","00000000002","VILA ANTONIO",0293,30,92734-900,"SANTO ANTONIO","SAO JOSE DO RIO PRETO","EXCLUVISE");

INSERT INTO TB_CLIENTE (NOME_CLI,TEL_CLI, CPFCLI ,LOGRACLI, NUMRECLI, COMPLEMENTO ,CEPCLI ,BAIRROCLI ,CIDADECLI, TIPOCLI)
VALUES (DENIS,"(17)90939-9430","96835184595","SAO DECLEOCIANO",0932,98,92837-343,"SAO DECLEOCIANO","SAO JOSE DO RIO PRETO",NORMAL);

INSERT INTO tb_produto (NOMEPROD ,VALORPROD, QTDPROD, MARCA ,FORNPROF) 
VALUES ("DESODORANTE",17.50,30,"REXONA","ATACADAO TRIDICO");

INSERT INTO tb_produto (NOMEPROD ,VALORPROD, QTDPROD, MARCA ,FORNPROF) 
VALUES ("CIGARRO",10.50,30,"MARLBORO","ATACADAO TRIDICO");

INSERT INTO tb_produto (NOMEPROD ,VALORPROD, QTDPROD, MARCA ,FORNPROF) 
VALUES ("VASSORA",19.00,30,"BARRADA","ATACADAO TRIDICO");

INSERT INTO tb_vendedor (NOMEVEND,FUNCVEND)
VALUES ("RICCI", "ATENDENTE");

INSERT INTO tb_vendedor (NOMEVEND,FUNCVEND)
VALUES ("FLAVIO",CHEFE);

INSERT INTO tb_pedido (CODCLI,CODVEND,DATAPED,TIPOENTREGA)
VALUES (45,53,"2025/09/03","RETIRADA");

INSERT INTO tb_itens (CODPRED,CODPROD,OBS)
VALUES (22,34,"ESTOQUE");

INSERT INTO tb_itens (CODPRED,CODPROD,OBS)
VALUES (22,34,"A VISTA");

























