/*CRIAÇÃO DO BANCO DE DADOS*/
CREATE DATABASE BDCONTATO;

USE BDCONTATO;/*COMANDO PARA SELECIONAR O BANCO A SER USADO*/

/*CRIAÇÃO DA TABELA CONTATO*/

CREATE TABLE TBCONTATO(
ID_CONTATO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (40) NOT NULL, 
ENDERECO VARCHAR (30),
EMPRESA VARCHAR (30)
);  
/*CRIAÇÃO DA TABELA TELEFONE*/

CREATE TABLE TBTELEFONE(
ID_TEL INT PRIMARY KEY AUTO_INCREMENT,
NUMERO VARCHAR (14),
COD_CONTATO INT NOT NULL,
FOREIGN KEY (COD_CONTATO) REFERENCES TBCONTATO (ID_CONTATO)
)ENGINE=INNODB;

/*CRIAÇÃO DA TABELA EMAIL*/

CREATE TABLE TBEMAIL(
ID_EMAIL INT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR (50),
COD_CONTATO INT NOT NULL,
FOREIGN KEY (COD_CONTATO) REFERENCES TBCONTATO(ID_CONTATO)
)ENGINE=INNODB;

/*INSERINDO DADOS NA TABELA TBCONTATO*/

INSERT INTO tbcontato(NOME, ENDERECO,EMPRESA)
VALUES ("RICCI","HIGIENOPOLIS","CAIXA"); 

INSERT INTO tbcontato(NOME, ENDERECO,EMPRESA)
VALUES ("CLAUDIO","CIDADE NOVA","BANCO DO BRASIL"); 

INSERT INTO tbcontato(NOME, ENDERECO,EMPRESA)
VALUES ("LULA","PLANALTO","RECEITA FEDERAL"); 

INSERT INTO tbcontato(NOME, ENDERECO,EMPRESA)
VALUES ("DENIS","SOLO SAGRADO","MCDONALDS"); 

INSERT INTO tbcontato(NOME, ENDERECO,EMPRESA)
VALUES ("GUSTAVO","ELDORADO","WEPINK"); 

/*INSERINDO DADOS DO TELEFONE*/
 INSERT INTO tbtelefone(NUMERO,COD_CONTATO)
 VALUES ("(17)9984-6435",1);
 
INSERT INTO tbtelefone(NUMERO,COD_CONTATO)
 VALUES ("(11)9674-9035",2);
 
INSERT INTO tbtelefone(NUMERO,COD_CONTATO)
 VALUES ("(16)9434-9035",3);
 
  INSERT INTO tbtelefone(NUMERO,COD_CONTATO)
 VALUES ("(16)99406-1610",4);
 
 INSERT INTO tbtelefone(NUMERO,COD_CONTATO)
 VALUES ("(17)9904-1232",5);
 
 
 INSERT INTO TBEMAIL(EMAIL,COD_CONTATO)
 VALUES ("RICCI@GMAIL.COM",1);
 
 INSERT INTO TBEMAIL(EMAIL,COD_CONTATO)
 VALUES ("CLAUDIO@GMAIL.COM",2);
 
 INSERT INTO TBEMAIL(EMAIL,COD_CONTATO)
 VALUES ("LULA@GMAIL.COM",3);
 
 INSERT INTO TBEMAIL(EMAIL,COD_CONTATO)
 VALUES ("DENIS@GMAIL.COM",4);
 
 INSERT INTO TBEMAIL(EMAIL,COD_CONTATO)
 VALUES ("GUSTAVO@GMAIL.COM",5);
 
 
 INSERT INTO TBEMAIL(EMAIL,COD_CONTATO)
 VALUES ("RICCI41K@GMAIL.COM",2);
 


/*INSERT INTO NOMETABELA(CAMPO1,CAMPO 2)*/
/*    "TEXTO"               'DATA'             
                 1,1.0                     */
/*VALUES(VALORCAMPO1,VALORCAMPO2)*/