CREATE DATABASE BDPET;

USE BDPET;

/*TABELA TUTOR*/
CREATE TABLE TBTUTOR(
IDTUTOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMETUTOR VARCHAR(40) NOT NULL,
CELTUTOR VARCHAR(13) NOT NULL,
CPFTUTOR VARCHAR(14),
EMAILTUTOR VARCHAR(30)
);

/*TABELA MEDICO*/
CREATE TABLE TBMEDICO(
IDMED INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMEMED VARCHAR(40) NOT NULL,
ESPEMED VARCHAR(30)
);

/*TABELA PET*/
CREATE TABLE TBPET(
IDPET INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CODTUTOR INT NOT NULL,
NOMEPET VARCHAR(30),
ESPECIEPET VARCHAR(25),
RACAPET VARCHAR(25),
DATANASPET DATE,
FOREIGN KEY (CODTUTOR) REFERENCES TBTUTOR(IDTUTOR)
)ENGINE=INNODB;

/*TABELA ATENDIMENTO*/
CREATE TABLE TBATENDIMENTO(
IDATEND INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CODMED INT NOT NULL,
CODPET INT NOT NULL,
DATAATEND DATE NOT NULL,
HORAATEND TIME NOT NULL,
ANOTAATEND VARCHAR(40),
FOREIGN KEY (CODMED) REFERENCES TBMEDICO(IDMED),
FOREIGN KEY (CODPET) REFERENCES TBPET(IDPET)
)ENGINE=INNODB;

/*INSERÇÃO DE DADOS TUTORES*/
INSERT INTO TBTUTOR (NOMETUTOR,CELTUTOR,CPFTUTOR,EMAILTUTOR) VALUES
("FERNANDO PEREIRA","(17)981324412","122.989.232/15","FERPEREIRA@GMAIL.COM"),
("JOÃO FLORES","(17)981111026","671.871.231/02","JAOFLORES@TERRA.COM.BR"),
("ANA PAULA SILVA","(17)981001641","221.432.222/09","ANINHASILVA21@GMAIL.COM"),
("JONAS BONES","(17)982226721","178.871.232/11","JJBB12@GMAIL.COM"),
("WILMA APARECIDA SILVA","(17)983231333","231.981.333/23","WILMA231@GMAIL.COM");

/*INSERÇÃO DE DADOS MEDICOS*/

INSERT INTO TBMEDICO(NOMEMED,ESPEMED)VALUES
("RICARDO HOLMES","GERAL"),
("MARIA HELENA","GASTRO"),
("JORGE SAYMES","ORTOPEDIA");

/* INSERÇÃO DE DADOS PET*/
INSERT INTO TBPET(CODTUTOR,NOMEPET,ESPECIEPET,RACAPET,DATANASPET)VALUES
(2,"XUXO","CÃO","POODLE","2020/05/23"),
(3,"MERY","GATO","SIAMÊS","2022/03/01"),
(1,"JERRY","PORCO DA ÍNDIA","PERUANO","2024/10/12"),
(2,"BOB","CÃO","BULDOGUE","2025/04/22"),
(4,"LINDA","GATO","PERSA","2024/11/10"),
(5,"PERLA","GATO","RAGDOLL","2025/02/22"),
(5,"JUDITE","COELHO","ANGORÁ","2025/03/14");

/*INSERÇÃO DE ATENDIMENTOS*/
INSERT INTO TBATENDIMENTO(CODMED,CODPET,DATAATEND,HORAATEND,ANOTAATEND)VALUES
(2,3,"2025/05/05","08:30","FEBRE E VÔMITO"),
(3,2,"2025/05/05","08:30","PERNA DIREITA DIANTEIRA LUXADA"),
(1,1,"2025/05/06","09:00","VACINA"),
(1,4,"2025/05/06","10:00","VACINA ANTIRRÁBICA"),
(2,5,"2025/05/07","09:30","DOENÇA DO CARRAPATO"),
(2,6,"2025/05/07","09:30","VACINA"),
(3,7,"2025/05/07","10:00","PESCOÇO COM INCHAÇO");

SELECT NOMETUTOR , CELTUTOR ,EMAILTUTOR
FROM tbtutor;

SELECT NOMETUTOR , CELTUTOR ,EMAILTUTOR
FROM tbtutor
WHERE NOMETUTOR = "JOÃO FLORES";

SELECT *
FROM tbmedico
WHERE ESPMED = "ORTOPEDIA";

SELECT NOMEPET,ESPECIEPET,RACAPET
FROM tbpet
WHERE ESPECIEPET= "CÃO";

SELECT NOMEPET, ESPECIEPET, RACAPET 
FROM tbpet
WHERE ESPECIEPET IN ("GATO", "PORCO DA ÍNDIA", "COELHO");

SELECT HORAATEND, ANOTAATEND, DATAATEND
FROM tbatendimento
WHERE DATAATEND = "2025/05/06";

SELECT *
FROM tbmedico
WHERE CODMED = 2;

SELECT ANOTAATEND,CODMED
FROM tbatendimento
WHERE CODPET = 2 AND CODMED = 3;

SELECT *
FROM tbpet
WHERE IDPET < 2 OR IDPET > 5;

SELECT  DISTINCT NOMEPET
FROM tbpet
WHERE ESPECIEPET = "CÃO" OR ESPECIEPET = "GATO";

SELECT NOMEPET, ESPECIEPET, RACAPET
FROM tbpet
WHERE DATANASPET BETWEEN "2024/10/12" AND "2024/11/10";

SELECT *
FROM tbpet
WHERE DATANASPET <= "2024/11/10";

/*exemplos de distinct*/
SELECT DISTINCT ESPECIEPET
FROM tbpet;

/*exemplo de between*/
SELECT *
FROM tbatendimento
WHERE DATAATEND BETWEEN "2025/05/06" AND "2025/05/07";

/*exemplo de in*/
SELECT *
FROM tbpet
WHERE RACAPET IN("POODLE","PERSA","ANGORÁ");

/*exemplo like*/
/* like texto%*/
SELECT ESPECIEPET
FROM tbpet
WHERE ESPECIEPET LIKE "POR%";

/*like %texto*/
SELECT *
FROM tbpet
WHERE ESPECIEPET LIKE "%O";

/*like %texto%*/
SELECT *
FROM tbpet
WHERE DATANASPET LIKE "%2024%"

/*not like*/
SELECT ESPECIEPET
FROM tbpet
WHERE ESPECIEPET NOT LIKE "CÃO";

/*order by*/
SELECT NOMEPET
FROM tbpet
WHERE ESPECIEPET NOT LIKE "CÃO"
ORDER BY NOMEPET ASC; 

/*Ex01*/

SELECT IDPET, NOMEPET, RACAPET
FROM tbpet
WHERE ESPECIEPET LIKE "GA%";

SELECT IDPET, RACAPET, CODTUTOR
FROM tbpet
WHERE ESPECIEPET IN ("GATO", "COELHO");

SELECT *
FROM tbatendimento
WHERE ANOTAATEND NOT LIKE "%VACINA%";

SELECT *
FROM tbatendimento
ORDER BY DATAATEND DESC;

SELECT *
FROM tbatendimento
WHERE HORAATEND BETWEEN "09:30:00" AND "11:00:00";

SELECT *
FROM tbpet
WHERE NOMEPET LIKE "%RY%";



 





