CREATE DATABASE BDESTOQUE;

USE BDESTOQUE;
CREATE TABLE TBPRODUTO (
idprod INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
nomeprod VARCHAR(25) NOT NULL,
tamprod CHAR(2)
);

CREATE TABLE TBFORNECEDOR (
idforn INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
nomeforn VARCHAR(30),
telforn VARCHAR(15),
respforn VARCHAR(35)
);

CREATE TABLE TBESTOQUE (
idest INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
codprod INTEGER NOT NULL,
codforn INTEGER NOT NULL,
entrada DATE NOT NULL,
qtdestoque INTEGER NOT NULL,
valorentrada DECIMAL(5,2) NOT NULL,
valorsaida DECIMAL(5,2) NOT NULL,
FOREIGN KEY(codprod) REFERENCES TBPRODUTO (idprod),
FOREIGN KEY(codforn) REFERENCES TBFORNECEDOR (idforn)
)ENGINE=INNODB;



/* DADOS TBPRODUTO */
INSERT INTO TBPRODUTO (NOMEPROD,TAMPROD)
VALUES("CALÇA","P"),
("CALÇA","M"),
("CALÇA","G"),
("BLUSA","P"),
("BLUSA","M"),
("BLUSA","G"),
("BLUSA","XG"),
("SAIA","P"),
("SAIA","M"),
("SAIA","G"),
("VESTIDO","PP"),
("VESTIDO","P"),
("VESTIDO","M"),
("VESTIDO","G");

/* DADOS TBFORNECEDOR */
INSERT INTO TBFORNECEDOR (nomeforn,telforn,respforn)
VALUES ("MMARCAS","(17)981322212","PEDRO JOÃO"),
("JJ","(17)32334213","JOÃO FILIPE"),
("SILVA","(17)32220987","FERNANDA"),
("SILVANA","(17)984532120","MARCELO");

/*DADOS ESTOQUE */
INSERT INTO TBESTOQUE
(codprod,codforn,entrada,qtdestoque,valorentrada,valorsaida)
VALUES (1,2,"2025/04/10",120,45.00,112.00),
(3,2,"2025/04/10",100,45.00,120.00),
(2,2,"2025/04/10",50,45.00,105.00),
(4,4,"2025/02/01",60,30.00,70.00),
(5,4,"2025/04/01",90,45.00,130.00),
(6,4,"2025/03/01",90,45.00,130.00),
(7,4,"2025/04/01",90,45.00,130.00),
(8,3,"2025/05/01",25,60.50,90.00),
(11,1,"2025/05/06",30,75.90,100.00),
(12,1,"2025/05/06",30,75.90,100.00),
(10,1,"2025/05/06",30,75.90,100.00),
(3,2,"2025/03/10",50,45.00,100.00),
(7,4,"2025/05/01",100,45.00,130.00);




/*SOMA*/
SELECT SUM(valorentrada) AS TOTAL, ENTRADA AS DIA
FROM tbestoque
WHERE ENTRADA = "2025/04/01";
/*AVG = AVERAGE MEDIA*/
SELECT VALORENTRADA AS MÉDIA,CODFORN AS FORNECEDOR
FROM tbestoque
WHERE CODFORN=4;

SELECT AVG (VALORENTRADA) AS MÉDIA,CODFORN AS FORNECEDOR
FROM tbestoque
WHERE CODFORN=4;
/*CONTAR*/
SELECT COUNT(*) AS TOTAL
FROM tbproduto
WHERE NOMEPROD="BLUSA";

SELECT VALORSAIDA,CODFORN
FROM tbestoque
WHERE CODFORN=2;
/*VALOR MINIMO*/
SELECT MIN(VALORSAIDA),CODFORN
FROM tbestoque
WHERE CODFORN=2;

/*VALOR MAXIMO*/
SELECT VALORSAIDA,CODFORN
FROM tbestoque
WHERE CODFORN=2;

SELECT MAX(VALORSAIDA),CODFORN
FROM tbestoque
WHERE CODFORN=2;

/*MULTIPLICAÇÃO*/
SELECT QTDESTOQUE*VALORSAIDA AS "TOTAL"
FROM tbestoque
WHERE IDEST=3;

SELECT SUM(QTDESTOQUE*VALORSAIDA)
FROM tbestoque;
/*DIVISAO*/
SELECT (QTDESTOQUE*VALORENTRADA)/2
FROM tbestoque
WHERE IDEST=3;

/*SOMA*/
SELECT QTDESTOQUE+5
FROM tbestoque
WHERE IDEST=3;

/*SUBTRAÇÃO*/
SELECT VALORSAIDA-VALORNENTRADA
FROM tbestoque
WHERE IDEST=3;






/*1*/
SELECT COUNT(*) AS TOTAL
FROM tbestoque
WHERE CODFORN = 2;

/*2*/
SELECT MIN(VALORSAIDA) AS MENOR_VALOR
FROM tbestoque;

/*3*/
SELECT COUNT(*) AS TOTAL
FROM tbestoque
WHERE  VALORSAIDA >= 100;

/*4*/
SELECT MAX(VALORENTRADA) AS VALOR_ENTRADA
FROM tbestoque
WHERE ENTRADA BETWEEN "2025-02-01" AND "2025-04-05";

/*5*/
SELECT AVG(QTDESTOQUE) AS MEDIA 
FROM tbestoque
WHERE ENTRADA = "2025-05-06";

/*6*/
SELECT SUM(VALORENTRADA) 
FROM tbestoque
WHERE CODFORN = 2;

/*7*/
SELECT COUNT(*) AS QTD
FROM tbproduto
WHERE TAMPROD = "P";

/*8*/
SELECT COUNT(*) AS QTD_TOTAL
FROM tbproduto;

/*9*/
SELECT (VALORENTRADA * QTDESTOQUE) AS TOTAL 
FROM tbestoque
WHERE IDEST = 8;

/*10*/
SELECT (VALORSAIDA - VALORENTRADA) * QTDESTOQUE AS TOTAL
FROM tbestoque
WHERE IDEST = 8;

/*11*/
SELECT SUM((VALORSAIDA - VALORENTRADA) * QTDESTOQUE) AS TOTAL
FROM tbestoque;

/*12*/
SELECT SUM(QTDESTOQUE) AS "?"
FROM tbestoque
WHERE ENTRADA="2025/05/06";
/*EXPLICAÇÃO
Logo esta cosulta eh q vai realizar a soma de todos os dados de quantidades de estoque dos produtos que deram a entrada no dia 2025/05/06
*/

/*1*/
SELECT *
FROM tbfornecedor;

SELECT nomeprod
FROM tbproduto
WHERE nomeprod LIKE "%A";

SELECT nomeprod, tamprod
FROM tbproduto
WHERE  nomeprod IN ("SAIA","BLUSA");

SELECT *
FROM tbestoque
WHERE ENTRADA BETWEEN "2025-04-01" AND "2025-05-01";


SELECT SUM(VALORENTRADA) AS TOTAL
FROM tbestoque
WHERE codforn=1;

SELECT COUNT(*)
FROM tbestoque
WHERE codforn=2;

SELECT (VALORENTRADA * QTDESTOQUE) AS TOTAL
FROM tbestoque
WHERE codprod=7;

SELECT VALORENTRADA,CODPROD,VALORSAIDA
FROM tbestoque
WHERE CODPROD BETWEEN 3 AND 8 ORDER BY CODPROD DESC;



